language: cpp
compiler:
- gcc
- clang

before_install:
  # Don't build if the last commit was from travis
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
- if [[ "$TRAVIS_COMMIT_MSG" = "$COMMIT_IGNORE_BUILD" ]]; then exit 0 ; fi

  # Configure git
- git config --global user.email "$USER_EMAIL"
- git config --global user.name "$USER_NAME"
- git config --global push.default simple
- git checkout $TRAVIS_BRANCH

install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq

  # Install valgrind
- sudo apt-get install -qq valgrind

  # Install g++
- if [ "$CXX" = "g++" ]; then
    sudo apt-get install -qq g++-4.8;
    export CXX="g++-4.8" CC="gcc-4.8";
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90;
  fi

  # Install clang
- if [ "$CXX" = "clang++" ]; then
    sudo apt-get install -qq clang;
    export CXX="clang++" CC="clang";
    sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 90;
    sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 90;
  fi

  # Install Biicode
- wget -O bii-ubuntu64.deb http://www.biicode.com/downloads/latest/ubuntu64
- "(sudo dpkg -i bii-ubuntu64.deb) && sudo apt-get -f install"
- bii --version
- rm bii-ubuntu64.deb

  # Install CMake
- wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-Linux-64.tar.gz
- tar -xzf cmake-3.0.2-Linux-64.tar.gz
- sudo cp -fR cmake-3.0.2-Linux-64/* /usr
- rm -rf cmake-3.0.2-Linux-64
- rm cmake-3.0.2-Linux-64.tar.gz

- export TRAVIS_CXX=$CXX

script:
- bii init -l
- bii configure -DBUILD_SHARED_LIBS=ON -DUS_BUILD_SHARED_LIBS=ON
- bii build
- valgrind --leak-check=full "bin/${USER}_${BLOCK_NAME}_test_main"

after_success:
  # Publish block
- bii user $USER -p $BII_PASSWORD
- bii --version
- if [[ -n $TRAVIS_TAG ]]; then bii publish -r --tag STABLE --versiontag $TRAVIS_TAG; fi
- if [[ -z $TRAVIS_TAG ]]; then bii publish -r; fi

  # If there are changes, commit them
- git config credential.helper "store --file=.git/credentials" 
- echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
- git add -A .
- git commit -m "$COMMIT_IGNORE_BUILD" 
- git remote -v
- git remote set-url origin https://github.com/$TRAVIS_REPO_SLUG.git 
- git push

env:
  global:
  - USER_EMAIL=azriel91@gmail.com
  - USER_NAME="azriel"
  - COMMIT_IGNORE_BUILD="Promoted version. ***travis***"
  - BLOCK_NAME=usserviceeventlistener
  - USER=azriel
  # BII_PASSWORD
  - secure: "Q+mPfWqrX8ULpiovLjTlsDlUl8GmBwMDDO1vFXUSTnpirVbIP5v/eDBbVW8u7SombPwvaX+Wipaz45yt5uFq+0vI4AfQYGHZHHcjZzTJgtSJI8jgWpIaxhpzQAfIHL6EeNuVPIqTLuJBEKqnME5u+P/7bgIg9kiq5o7GAMioKGo="
  # GITHUB_TOKEN
  - secure: "g/5tIVCJNQw+dtPRyckMMHh88w5kkKY1+k62TlQ/ERdy2G4J3vAnW3B7bGpfzklqGV/72YQekiZxHvpLTUA4vixO+MPvDBK9igSYqZLflRKrQxH0X6T/P8fifYeCv5kr5VeDwnxQ4nr0054mehkHLuJkE7faDpxdXlsDMtlKpO4="
